# Site settings
title: How EU Law becomes EEA Law
description: >-
  The European Economic Area (EEA) Agreement enables Iceland, Liechtenstein and Norway (EEA EFTA States) to participate in the EU Internal Market. It covers the free movement of goods, services, capital and persons, competition and state aid rules, and certain horizontal and flanking areas.

# GitHub Pages
# url: "https://eaudeweb.github.io"
# baseurl: "/efta_eea-procedure"

# design.eaudeweb.ro
# url: "http://design.eaudeweb.ro"
# baseurl: "/efta"

# localhost
# url: ""
# baseurl: ""

# EFTA production website
url: "http://eealaw.efta.int"
baseurl: ""

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "de", "is", "no"]

exclude:
  - docker-compose.yml
  - efta_presentation-howEULawBecomesEEALaw-v1.0.pdf
  - README.md
  - Gemfile
  - Gemfile.lock
